# generated by datamodel-codegen:
#   filename:  langgraph/graph.schema.json
#   timestamp: 2026-01-22T11:25:30+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, confloat, conint


class Schema(Enum):
    langgraph_v1 = 'langgraph.v1'


class Plane(Enum):
    node = 'node'
    python = 'python'


class NodeStatus(Enum):
    pending = 'pending'
    ready = 'ready'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    skipped = 'skipped'


class ErrorInfo(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message: str | None = Field(None, description='Human-readable error message.')
    code: str | None = Field(None, description='Machine-readable error code.')
    details: dict[str, Any] | list[Any] | str | float | bool | None = Field(
        None, description='Arbitrary structured details about the failure.'
    )


class Retries(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: conint(ge=0) | None = Field(
        None, description='Current attempt number for this node.'
    )
    maxAttempts: conint(ge=1) | None = Field(
        None, description='Maximum allowed attempts for this node.'
    )


class Node(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., description='Unique node identifier within this workflow.')
    name: str | None = Field(
        None, description='Optional human-friendly label for the node.'
    )
    service: str = Field(
        ...,
        description="Symbolic service/capability identifier (e.g. a capabilities.json `id` like 'generate.f5_to_tts').",
    )
    plane: Plane
    status: NodeStatus
    params: dict[str, Any] | None = Field(
        None,
        description='Planner-defined parameters for this node (mapped onto capability input/parameters).',
    )
    input: dict[str, Any] | list[Any] | str | float | bool | None = Field(
        None,
        description='Optional snapshot of node-specific input (resolved from context/previous outputs).',
    )
    output: dict[str, Any] | list[Any] | str | float | bool | None = Field(
        None,
        description='Node output payload or artifact references; stored as part of the graph for later nodes.',
    )
    error: ErrorInfo | None = None
    retries: Retries | None = Field(
        None, description='Retry bookkeeping, if implemented (attempt count etc).'
    )
    tags: list[str] | None = Field(
        None, description='Optional tags for debugging, grouping, or analytics.'
    )
    telemetry: dict[str, Any] | None = Field(
        None, description='Optional telemetry hints (metrics keys, spans, etc.).'
    )
    progressWeight: confloat(ge=0.0) | None = Field(
        None,
        description='Relative share of overall progress this node contributes; optional, defaults to 1.',
    )


class Kind(Enum):
    normal = 'normal'
    on_success = 'on_success'
    on_failure = 'on_failure'


class Edge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: str = Field(..., alias='from', description='Source node id.')
    to: str = Field(..., description='Target node id.')
    kind: Kind | None = Field(
        'normal', description='Optional edge kind to support conditional flows.'
    )
    metadata: dict[str, Any] | None = Field(
        None,
        description='Optional edge-level metadata (e.g. condition expressions, weights).',
    )


class LanggraphWorkflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: Schema = Field(
        ...,
        alias='schema',
        description='Logical schema version of the LangGraph document.',
    )
    workflowId: str = Field(
        ...,
        description='Stable identifier for this workflow instance (distinct from Job id, which wraps this graph).',
    )
    context: dict[str, Any] | None = Field(
        None,
        description='Shared, plane-agnostic context object accessible to all nodes.',
    )
    metadata: dict[str, Any] | None = Field(
        None,
        description='Optional planner/runtime metadata (non-critical for execution).',
    )
    nodes: list[Node] = Field(
        ..., description='All nodes in the workflow DAG.', min_length=1
    )
    edges: list[Edge] = Field(
        ..., description='Directed edges representing dependencies between nodes.'
    )
