# generated by datamodel-codegen:
#   filename:  capabilities/capability.schema.json
#   timestamp: 2025-11-24T17:07:14+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from . import defs_schema


class Plane(Enum):
    node = 'node'
    python = 'python'


class Io(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: defs_schema.JsonSchemaFragment = Field(
        ..., description='JSON Schema describing accepted payloads.'
    )
    output: defs_schema.JsonSchemaFragment = Field(
        ..., description='JSON Schema describing the response.'
    )


class Capability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., description='Unique string identifier (machine readable).')
    label: str = Field(
        ..., description='Human-readable label used in UIs and agent planners.'
    )
    description: str = Field(..., description='Summary of what the capability does.')
    version: str = Field(
        ..., description='Semantic version of the manifest defining this capability.'
    )
    plane: Plane = Field(..., description='Execution plane hint (e.g. node, python).')
    runtime: defs_schema.Runtime
    handler: defs_schema.Handler
    io: Io = Field(
        ...,
        description='JSON Schemas describing accepted input payloads and expected output responses.',
        title='Input/Output Schema Definitions',
    )
    parameters: Optional[List[defs_schema.Parameter]] = Field(
        None,
        description='Optional structured parameter list (name/type/description/required).',
    )
    examples: Optional[List] = Field(
        None, description='Example payloads and responses used for planner grounding.'
    )
    telemetry: Optional[defs_schema.Telemetry] = Field(
        None, description='Flags describing progress events or custom metrics.'
    )
    security: Optional[defs_schema.Security] = Field(
        None, description='Whether secrets or scoped credentials are required.'
    )
    contracts: Optional[defs_schema.Contracts] = Field(
        None,
        description='Operational guarantees such as idempotency or expected side effects.',
    )
