# generated by datamodel-codegen:
#   filename:  capabilities/combined-manifest.schema.json
#   timestamp: 2025-11-24T10:24:07+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import capability_schema


class Plane(Enum):
    node = 'node'


class Control(BaseModel):
    plane: Plane = Field(..., description='Source plane identifier.')
    number: float = Field(
        ..., description='Number of capabilities contributed by the control plane.'
    )


class Plane2(Enum):
    python = 'python'


class Worker(BaseModel):
    plane: Plane2 = Field(..., description='Source plane identifier.')
    number: float = Field(
        ..., description='Number of capabilities contributed by the worker plane.'
    )


class Sources(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    control: Control = Field(
        ..., description='Source information for the control plane (node).'
    )
    worker: Worker = Field(
        ..., description='Source information for the worker plane (python).'
    )


class CapabilitiesManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    generatedAt: AwareDatetime = Field(
        ...,
        description='Timestamp representing when the combined manifest was assembled.',
    )
    capabilities: List[capability_schema.Capability] = Field(
        ..., description='All capabilities across all execution planes.'
    )
    sources: Sources = Field(
        ...,
        description='Metadata describing how many capabilities originated from each plane.',
    )
