# generated by datamodel-codegen:
#   filename:  capabilities/defs.schema.json
#   timestamp: 2026-01-22T11:25:30+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class SharedDefinitions(BaseModel):
    pass


class JsonSchemaFragment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )


class Parameter(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str = Field(..., description='Parameter name.')
    type: str = Field(
        ..., description='Expected parameter data type (string, number, boolean, etc.).'
    )
    description: str | None = Field(
        None, description='Human-readable explanation of the parameter.'
    )
    required: bool | None = Field(
        None, description='Whether the parameter must be provided by the caller.'
    )
    default: Any | None = Field(
        None, description='Optional default value used if the parameter is omitted.'
    )


class Handler(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    module: str = Field(..., description='Path to the module exporting the resolver.')
    method: str = Field(..., description='Exported method or function name to invoke.')


class Kind(Enum):
    cpu = 'cpu'
    gpu = 'gpu'


class Runtime(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: Kind = Field(
        ...,
        description='Execution plane: cpu or gpu. Node-plane capabilities always use cpu.',
    )
    timeoutSeconds: float | None = Field(
        None, description='Execution timeout guard in seconds.'
    )
    concurrency: float = Field(
        ..., description='Maximum allowed concurrent invocations.'
    )


class Telemetry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    emitsProgressEvents: bool | None = Field(
        None, description='Whether this capability emits progress events.'
    )
    metrics: list[str] | None = Field(
        None, description='List of metric identifiers emitted during execution.'
    )


class Security(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    requiresSecrets: bool | None = Field(
        None,
        description='Whether this capability requires access to secrets or secure credentials.',
    )


class Contracts(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    idempotent: bool | None = Field(
        None,
        description='Whether invoking the capability multiple times produces the same result.',
    )
    sideEffects: str | None = Field(
        None,
        description='Description of any operational side effects (e.g., persistent-storage-write).',
    )
