# generated by datamodel-codegen:
#   filename:  capabilities/plane-manifest.schema.json
#   timestamp: 2025-11-15T17:03:14+00:00

from __future__ import annotations

from datetime import datetime
from typing import List

from pydantic import BaseModel, Extra, Field

from . import capability_schema


class PlaneCapabilityManifest(BaseModel):
    class Config:
        extra = Extra.forbid

    generatedAt: datetime = Field(
        ..., description='Timestamp when this manifest was generated.'
    )
    capabilities: List[capability_schema.Capability] = Field(
        ..., description='List of capabilities supported by this plane.'
    )
