# generated by datamodel-codegen:
#   filename:  capabilities/plane-manifest.schema.json
#   timestamp: 2025-11-25T19:50:54+00:00

from __future__ import annotations

from typing import List

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import capability_schema


class PlaneCapabilityManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    generatedAt: AwareDatetime = Field(
        ..., description='Timestamp when this manifest was generated.'
    )
    capabilities: List[capability_schema.Capability] = Field(
        ..., description='List of capabilities supported by this plane.'
    )
