# generated by datamodel-codegen:
#   filename:  redis/redis.config.schema.json
#   timestamp: 2025-12-03T14:44:53+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Streams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    info: str = Field(
        ...,
        description="Root name of stream for exchanging high level information (e.g. 'stream:info:data').",
    )
    process: str = Field(
        ...,
        description="Root name of stream for exchanging job messages (e.g. 'stream:process:data').",
    )
    plan: Optional[str] = Field(
        None,
        description="Root name of stream for exchanging planner messages (e.g. 'stream:plan:control').",
    )


class Channels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    progress: str = Field(
        ...,
        description="Channel onto which jobs publish their progress (e.g. 'channel:progress').",
    )
    status: str = Field(
        ...,
        description="Channel onto which jobs publish their status (e.g. 'channel:status').",
    )
    data: str = Field(
        ...,
        description="Channel onto which jobs publish intermediate generic data (e.g. 'channel:data').",
    )


class Available(BaseModel):
    GET_CAPABILITIES: str = Field(..., description='Worker task mapped to this job.')
    PROCESS_GRAPH: str = Field(..., description='Worker task mapped to this job.')


class Jobs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: Optional[Available] = Field(
        None,
        description='List of mappings of available jobs supported by the Redis bridge, to worker tasks.',
    )
    ttl: conint(ge=1) = Field(
        ..., description='Job keys TTL in Redis, in seconds (e.g. 43200 for 12 hours).'
    )


class RedisConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: constr(pattern=r'^redis://.+') = Field(
        ..., description="Redis connection string (e.g. 'redis://redis:6379')."
    )
    streams: Streams = Field(
        ..., description='List of Redis streams used by the bridge.'
    )
    channels: Channels = Field(
        ..., description='List of pub/sub channels used by the bridge.'
    )
    jobs: Jobs = Field(..., description='Configuration for jobs.')
