# generated by datamodel-codegen:
#   filename:  redis/redis.config.schema.json
#   timestamp: 2025-12-03T19:17:48+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Streams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    control: str = Field(
        ..., description='Stream for advertising jobs at control plane.'
    )
    data: str = Field(..., description='Stream for advertising jobs at data plane.')


class Channels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    progress: str = Field(
        ...,
        description="Channel onto which jobs publish their progress (e.g. 'channel:progress').",
    )
    status: str = Field(
        ...,
        description="Channel onto which jobs publish their status (e.g. 'channel:status').",
    )
    data: str = Field(
        ...,
        description="Channel onto which jobs publish intermediate generic data (e.g. 'channel:data').",
    )


class Jobs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ttl: conint(ge=1) = Field(
        ..., description='Job keys TTL in Redis, in seconds (e.g. 43200 for 12 hours).'
    )


class Pipelines(BaseModel):
    PROCESS: str = Field(
        ...,
        description='Planner request type for creating execution pipelines for generic graphs.',
    )
    TRAIN_GENERATE: str = Field(
        ...,
        description='Planner request type for creating execution pipelines combining training and generation.',
    )
    GENERATE: str = Field(
        ...,
        description='Planner request type for creating execution pipelines for generation.',
    )


class Planning(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pipelines: Pipelines = Field(
        ...,
        description='List of mappings of available jobs supported by the Redis bridge, to worker tasks.',
    )


class RedisConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: constr(pattern=r'^redis://.+') = Field(
        ..., description="Redis connection string (e.g. 'redis://redis:6379')."
    )
    streams: Streams = Field(
        ..., description='List of Redis streams used by the bridge.'
    )
    channels: Channels = Field(
        ..., description='List of pub/sub channels used by the bridge.'
    )
    jobs: Jobs = Field(..., description='Configuration for jobs.')
    planning: Optional[Planning] = Field(None, description='Configuration for planner.')
