# generated by datamodel-codegen:
#   filename:  jobs/job-messaging.schema.json
#   timestamp: 2025-11-15T17:03:14+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Extra, Field, confloat


class JobMessagingSchemas(BaseModel):
    pass


class JobMessage(BaseModel):
    class Config:
        extra = Extra.forbid

    xid: str = Field(..., description='Redis Stream entry ID')
    stream: str = Field(..., description='Stream name')
    jobId: str = Field(..., description='Unique job ID')
    name: str = Field(..., description='Job type identifier (train/generate/etc.)')
    created: Optional[str] = Field(None, description='Timestamp in ms (stringified)')
    input: Optional[str] = Field(
        None, description='Generic data input serialized to string'
    )


class JobStatus(Enum):
    advertised = 'advertised'
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class DataUpdate(BaseModel):
    class Config:
        extra = Extra.forbid

    jobId: str
    data: str
    created: datetime


class ProgressUpdate(BaseModel):
    class Config:
        extra = Extra.forbid

    jobId: str
    progress: confloat(ge=0.0, le=1.0) = Field(
        ..., description='Normalized progress value between 0 and 1 inclusive'
    )
    created: datetime


class StatusUpdate(BaseModel):
    class Config:
        extra = Extra.forbid

    jobId: str
    status: JobStatus
    created: datetime
