{
 "title": "Monitoring: cadvisor",
 "description": "Customized for MySpinBot infra based on Docker monitoring (15798)",
 "tags": [
  "cadvisor",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "cadvisor" }
  ]
 },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"$job\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{job=~\"$job\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"$job\"}[$__rate_interval]) * 100) "
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{job=~\"cadvisor\"}[$__rate_interval]) ) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_usage_bytes{job=\"$job\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_network_receive_bytes_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "recv {{container}}"
    },
    {
     "expr": "-(sum by (container) (rate(container_network_transmit_bytes_total{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "trans {{container}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_fs_reads_bytes_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "read {{container}}"
    },
    {
     "expr": "-(sum by (container) (rate(container_fs_writes_bytes_total{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "write {{container}}"
    }
   ]
  }
 ]
}