{
 "title": "Monitoring: traefik",
 "description": "Customized for MySpinBot infra based on Router dashboard for Traefik on Kubernetes (18111)",
 "tags": [
  "prometheus",
  "proxy",
  "traefik"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "entrypoint",
    "query": {
     "query": "label_values(traefik_entrypoint_open_connections, entrypoint)"
    }
   },
   {
    "name": "router",
    "query": {
     "query": "label_values(traefik_router_open_connections, router)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top15 requested routers per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Reqs" } },
   "targets": [
    {
     "expr": "topk(15,\n  label_replace(\n      sum by (code, router)\n        (increase(traefik_router_requests_total{router=~\"$router.*\",protocol=\"http\"}[1m:1m]))>0,\n        \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\"\n  )\n)",
     "legendFormat": "[{{code}}] on {{router}}"
    }
   ]
  },
  {
   "title": "Http Code ",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (method, code)\n(rate(traefik_router_requests_total{router=~\"$router.*\",protocol=\"http\"}[1m])) ",
     "legendFormat": "{{code}} [{{method}}]"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "description": "https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method) + \n sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"1.2\",code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method)) / 2 / \n sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Top slow services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5,\n    label_replace(\n        traefik_router_request_duration_seconds_sum{router=~\"$router.*\",protocol=\"http\"} / \n          traefik_router_request_duration_seconds_count{router=~\"$router.*\",protocol=\"http\"},\n        \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\")\n)\n\n",
     "legendFormat": "{{code}} [{{method}}] on {{router}}"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\"}[1m])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Services failing SLO of 1200ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  1 - (sum by (router)\n    (rate(traefik_router_request_duration_seconds_bucket{le=\"1.2\",router=~\"$router.*\"}[5m])) / sum by (router) \n    (rate(traefik_router_request_duration_seconds_count{router=~\"$router.*\"}[5m]))\n  ) > 0,\n  \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\"\n)",
     "legendFormat": "{{router}}"
    }
   ]
  },
  {
   "title": "Services failing SLO of 300ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  1 - (sum by (router)\n    (rate(traefik_router_request_duration_seconds_bucket{le=\"0.3\",router=~\"$router.*\"}[5m])) / sum by (router) \n    (rate(traefik_router_request_duration_seconds_count{router=~\"$router.*\"}[5m]))\n  ) > 0,\n  \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\"\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "2xx",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Reqs" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (router,method,code) \n          (increase(traefik_router_requests_total{router=~\"$router.*\",code=~\"2..\",protocol=\"http\"}[1m:1m])),\n        \"service\", \"$1\", \"router\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{code}} [{{method}}] on {{service}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Reqs" } },
   "targets": [
    {
     "expr": "    label_replace(\n        sum by (router,method,code) \n          (increase(traefik_router_requests_total{router=~\"$router.*\",code=~\"5..\",protocol=\"http\"}[1m:1m])),\n        \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\"\n        )\n",
     "legendFormat": "{{code}} [{{method}}] on {{router}}"
    }
   ]
  },
  {
   "title": "Other codes ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Reqs" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (router,method,code) \n          (increase(traefik_router_requests_total{router=~\"$router.*\",code!~\"2..|5..\",protocol=\"http\"}[1m:1m])),\n        \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\"\n        )\n)",
     "legendFormat": "{{code}} [{{method}}] on {{router}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (router,method) \n          (rate(traefik_router_requests_bytes_total{router=~\"$router.*\",protocol=\"http\"}[1m])) > 0,\n        \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{method}} on {{router}}"
    }
   ]
  },
  {
   "title": "Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (router,method) \n          (rate(traefik_router_responses_bytes_total{router=~\"$router.*\",protocol=\"http\"}[1m])) > 0,\n        \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{method}} on {{router}}"
    }
   ]
  },
  {
   "title": "Connections per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(traefik_router_open_connections{router=~\"$router.*\"}) by (router),\n    \"service\", \"$1\", \"router\", \"([^-]+-[^-]+).*\")",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Connections per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{entrypoint=~\"$entrypoint\"}) by (entrypoint)\n",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  }
 ]
}