{
 "title": "Monitoring: websocket",
 "tags": [
  "websocket",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "WS Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "websocket_clients_connected" }
   ]
  },
  {
   "title": "Send / Receive Ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ratio" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(websocket_messages_sent_total[5m])) / (rate(websocket_messages_received_total[5m]))"
    }
   ]
  },
  {
   "title": "WebSocket Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errors/s" } },
   "targets": [
    {
     "expr": "rate(websocket_errors_total[5m])"
    }
   ]
  },
  {
   "title": "Connections per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "connections/s" } },
   "targets": [
    {
     "expr": "rate(websocket_connections_total[5m])"
    }
   ]
  },
  {
   "title": "Client Lifetime (p50, p90)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(websocket_client_lifetime_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(websocket_client_lifetime_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Messages Sent / Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "msgs/s" } },
   "targets": [
    {
     "expr": "rate(websocket_messages_sent_total[1m])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(websocket_messages_received_total[1m])",
     "legendFormat": "received"
    }
   ]
  }
 ]
}