# generated by datamodel-codegen:
#   filename:  storage/artifact.schema.json
#   timestamp: 2025-11-26T14:19:26+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ArtifactSchemas(BaseModel):
    pass


class ArtifactMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bucket: str = Field(..., description='MinIO bucket where the artifact is stored.')
    key: str = Field(..., description='Object key inside the MinIO bucket.')
    size_bytes: int = Field(..., description='Size of the artifact in bytes.')
    created_at: AwareDatetime = Field(
        ..., description='Timestamp when the artifact was created.'
    )
    content_type: Optional[str] = Field(
        None, description="Optional MIME type of the artifact (e.g. 'image/png')."
    )


class ArtifactUploadResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ok: bool = Field(..., description='Indicates whether the upload was successful.')
    meta: ArtifactMeta
